#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int massa = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int tamanho = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btn01 = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int btn1 = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int btnMenu = 2131099663;
			
			// aapt resource value: 0x7f06001a
			public const int btnMenuCilindro = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int btnMenuPizza = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int btnMenuRadioColor = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int btnOk = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int calcAreaCilindro = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int checkIngBacon = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int checkIngCebola = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int checkIngCheddar = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int checkIngFigo = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int checkIngGorgonzola = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int checkIngPeperoni = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int checkIngPresutoParma = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int edTextAltura = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int edTextRaio = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int radioGroup = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int ratingBar = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int rbAzul = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int rbVermelho = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int spMassa = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int spTamanho = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int tituloPizza = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int txtIngredientes = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int txtMassa = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int txtResultado = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int txtTamanho = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AreaCilindro = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PizzaLayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int PopupLayout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RadioGroupColorLayout = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ResultadoAreaCilindro = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menuPopup = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int ingBacon = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int ingCebola = 2130903041;
			
			// aapt resource value: 0x7f030004
			public const int ingCheddar = 2130903044;
			
			// aapt resource value: 0x7f030007
			public const int ingFigoAbacaxi = 2130903047;
			
			// aapt resource value: 0x7f030005
			public const int ingGorgonzola = 2130903045;
			
			// aapt resource value: 0x7f030003
			public const int ingPeperoni = 2130903043;
			
			// aapt resource value: 0x7f030006
			public const int ingPresunto = 2130903046;
			
			// aapt resource value: 0x7f030008
			public const int tagPizza = 2130903048;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
